"""Generated AIFA AC capability metadata from Firebase Remote Config."""
from __future__ import annotations

# Generated from reverse/firebase_activate.json by tools/regen_ac_catalog.py.
# Do NOT edit by hand — re-run the tool after refreshing the Firebase
# snapshot. See docs/regen-ac-catalog.md.

AC_AVAILABLE_MODES_BY_DEVICE_CODE: dict[str, tuple[str, ...]] = {
    '1': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '2': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '3': ('cool', 'heat', 'fan', 'dry'),
    '4': ('auto', 'cool', 'heat', 'dry'),
    '5': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '6': ('cool', 'heat', 'fan', 'dry'),
    '7': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '8': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '9': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '10': ('cool', 'dry'),
    '11': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '12': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '13': ('cool', 'fan', 'dry'),
    '14': ('cool', 'heat', 'fan', 'dry'),
    '15': ('cool', 'fan', 'dry'),
    '16': (),
    '17': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '18': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '19': (),
    '20': ('auto', 'cool', 'heat', 'dry'),
    '21': ('cool', 'dry'),
    '22': ('cool', 'dry'),
    '23': ('cool', 'fan', 'dry'),
    '24': ('auto', 'cool', 'fan', 'dry'),
    '25': ('cool', 'fan', 'dry'),
    '26': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '27': ('auto', 'cool', 'fan', 'dry'),
    '28': ('cool', 'heat', 'fan', 'dry'),
    '29': ('cool', 'heat', 'fan', 'dry'),
    '30': ('cool', 'fan', 'dry'),
    '31': ('cool', 'fan', 'dry'),
    '32': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '33': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '34': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '35': ('auto', 'cool', 'fan', 'dry'),
    '36': ('cool', 'heat', 'dry'),
    '37': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '38': ('auto', 'cool', 'fan', 'dry'),
    '39': ('auto', 'cool', 'fan', 'dry'),
    '40': ('cool', 'fan', 'dry'),
    '41': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '42': ('auto', 'cool', 'fan', 'dry'),
    '43': ('auto', 'cool', 'fan', 'dry'),
    '44': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '45': ('cool', 'fan', 'dry'),
    '46': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '47': ('cool', 'fan', 'dry'),
    '48': ('cool', 'fan', 'dry'),
    '49': ('auto', 'cool', 'fan', 'dry'),
    '50': ('auto', 'cool', 'fan', 'dry'),
    '51': ('auto', 'cool', 'fan', 'dry'),
    '52': ('auto', 'cool', 'fan', 'dry'),
    '53': ('auto', 'cool', 'fan', 'dry'),
    '54': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '55': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '56': ('auto', 'cool', 'fan', 'dry'),
    '57': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '58': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '59': ('cool', 'fan', 'dry'),
    '60': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '61': ('cool', 'fan', 'dry'),
    '62': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '63': ('auto', 'cool', 'fan', 'dry'),
    '64': ('auto', 'cool', 'heat', 'dry'),
    '65': ('auto', 'cool', 'fan', 'dry'),
    '66': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '67': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '68': ('cool', 'fan', 'dry'),
    '69': ('auto', 'cool', 'fan', 'dry'),
    '70': ('auto', 'cool', 'fan', 'dry'),
    '71': ('auto', 'cool', 'fan', 'dry'),
    '72': ('cool', 'fan', 'dry'),
    '73': ('auto', 'cool', 'heat', 'dry'),
    '74': ('auto', 'cool', 'fan', 'dry'),
    '75': ('auto', 'cool', 'fan', 'dry'),
    '76': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '77': ('cool', 'fan', 'dry'),
    '78': ('cool', 'fan', 'dry'),
    '79': ('auto', 'cool', 'fan', 'dry'),
    '80': ('auto', 'cool', 'fan', 'dry'),
    '81': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '82': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '83': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '84': ('cool', 'fan'),
    '85': ('auto', 'cool', 'heat', 'dry'),
    '86': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '87': ('auto', 'cool', 'fan', 'dry'),
    '88': ('cool', 'fan', 'dry'),
    '89': ('auto', 'cool', 'fan', 'dry'),
    '90': ('cool', 'heat', 'fan', 'dry'),
    '91': ('cool', 'fan', 'dry'),
    '92': ('cool', 'fan', 'dry'),
    '93': ('cool', 'dry'),
    '94': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '95': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '96': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '97': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '98': ('auto', 'cool', 'fan', 'dry'),
    '99': ('cool', 'dry'),
    '100': ('cool', 'fan'),
    '101': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '102': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '103': ('auto', 'cool', 'heat', 'dry'),
    '104': ('cool', 'fan', 'dry'),
    '105': ('cool', 'fan', 'dry'),
    '106': ('auto', 'cool', 'fan', 'dry'),
    '107': ('auto', 'cool', 'fan', 'dry'),
    '108': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '109': ('auto', 'cool', 'heat', 'dry'),
    '110': ('cool', 'fan', 'dry'),
    '111': ('cool', 'heat', 'fan', 'dry'),
    '112': ('auto', 'cool', 'fan', 'dry'),
    '113': ('auto', 'cool'),
    '114': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '115': (),
    '116': (),
    '117': (),
    '118': (),
    '119': (),
    '120': (),
    '121': (),
    '122': (),
    '123': (),
    '124': (),
    '125': (),
    '126': (),
    '127': ('auto', 'cool', 'dry'),
    '128': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '129': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '130': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '131': ('cool', 'heat', 'fan', 'dry'),
    '132': ('auto', 'cool', 'dry'),
    '133': ('auto', 'cool', 'fan', 'dry'),
    '134': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '135': ('auto', 'cool', 'heat', 'dry'),
    '136': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '137': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '138': ('cool', 'fan', 'dry'),
    '139': ('auto', 'cool', 'fan', 'dry'),
    '140': ('cool', 'fan', 'dry'),
    '141': ('cool', 'fan', 'dry'),
    '142': ('auto', 'cool', 'heat', 'dry'),
    '143': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '144': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '145': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '146': ('auto', 'cool', 'dry'),
    '147': ('auto', 'cool', 'heat', 'dry'),
    '148': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '149': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '150': ('cool', 'heat', 'dry'),
    '151': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '152': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '153': ('cool', 'heat', 'fan', 'dry'),
    '154': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '155': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '156': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '157': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '158': ('auto', 'cool', 'heat', 'dry'),
    '159': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '160': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '161': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '162': (),
    '163': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '164': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '165': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '166': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '167': ('cool', 'fan', 'dry'),
    '168': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '169': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '170': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '171': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '172': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '173': ('auto', 'cool', 'dry'),
    '174': ('auto', 'cool', 'heat', 'dry'),
    '175': ('auto', 'cool', 'heat', 'dry'),
    '176': ('auto', 'cool', 'heat', 'dry'),
    '177': ('cool', 'heat', 'dry'),
    '178': ('auto', 'cool', 'heat', 'dry'),
    '179': ('cool', 'heat', 'dry'),
    '180': (),
    '181': ('cool', 'heat', 'fan', 'dry'),
    '182': ('cool', 'heat', 'dry'),
    '183': ('cool', 'heat', 'dry'),
    '184': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '185': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '186': ('auto', 'cool', 'heat', 'dry'),
    '187': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '188': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '189': ('cool', 'heat', 'dry'),
    '190': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '191': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '192': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '193': ('auto', 'cool', 'fan', 'dry'),
    '194': ('cool', 'heat', 'fan', 'dry'),
    '195': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '196': ('auto', 'cool', 'fan', 'dry'),
    '197': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '198': ('cool', 'dry'),
    '199': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '200': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '201': ('auto', 'cool', 'heat', 'dry'),
    '202': ('auto', 'cool', 'heat', 'dry'),
    '203': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '204': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '205': ('cool', 'heat', 'fan', 'dry'),
    '206': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '207': ('cool', 'fan', 'dry'),
    '208': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '209': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '210': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '211': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '212': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '213': ('auto', 'cool', 'fan', 'dry'),
    '214': ('auto', 'cool', 'heat', 'dry'),
    '215': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '216': ('cool', 'dry'),
    '217': ('auto', 'cool', 'fan', 'dry'),
    '218': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '250': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '251': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '252': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '253': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '254': ('cool', 'fan', 'dry'),
    '255': ('auto', 'cool', 'heat', 'dry'),
    '256': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '257': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '258': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '259': ('auto', 'cool', 'heat', 'dry'),
    '260': (),
    '261': ('cool', 'fan', 'dry'),
    '262': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '263': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '264': ('auto', 'cool', 'heat', 'dry'),
    '265': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '266': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '267': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '268': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '269': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '270': ('cool', 'heat', 'dry'),
    '271': ('cool', 'fan', 'dry'),
    '272': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '273': ('cool', 'heat', 'fan', 'dry'),
    '274': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '275': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '276': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '277': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '278': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '279': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '280': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '281': ('auto', 'fan', 'dry'),
    '282': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '283': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '284': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '285': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '286': ('auto', 'cool', 'heat', 'dry'),
    '287': ('cool', 'fan', 'dry'),
    '288': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '289': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '290': ('cool', 'heat', 'fan', 'dry'),
    '291': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '292': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '293': (),
    '294': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '295': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '296': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '297': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '298': ('cool', 'fan', 'dry'),
    '299': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '300': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '301': ('auto', 'cool', 'heat', 'fan'),
    '302': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '303': ('auto', 'cool', 'fan', 'dry'),
    '304': ('auto', 'cool', 'fan', 'dry'),
    '305': ('auto', 'cool', 'fan', 'dry'),
    '306': ('auto', 'cool', 'fan', 'dry'),
    '307': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '308': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '309': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '310': ('cool', 'fan', 'dry'),
    '311': ('cool', 'heat', 'fan', 'dry'),
    '312': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '313': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '314': ('cool', 'fan', 'dry'),
    '315': (),
    '316': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '317': (),
    '318': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '319': ('auto', 'cool', 'heat', 'dry'),
    '320': ('auto', 'cool', 'heat', 'dry'),
    '321': ('auto', 'cool', 'heat', 'dry'),
    '322': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '323': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '324': ('cool', 'heat', 'fan', 'dry'),
    '325': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '326': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '327': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '328': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '329': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '330': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '331': ('cool', 'heat', 'fan', 'dry'),
    '332': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '400': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '401': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '420': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '421': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '422': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '423': ('cool', 'fan', 'dry'),
    '424': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '425': ('auto', 'cool', 'heat', 'dry'),
    '426': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '427': ('auto', 'cool', 'heat', 'dry'),
    '428': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '429': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '430': ('cool', 'fan', 'dry'),
    '431': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '432': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '433': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '434': ('auto', 'cool', 'fan', 'dry'),
    '435': (),
    '436': ('auto', 'cool', 'fan', 'dry'),
    '437': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '438': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '439': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '440': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '441': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '442': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '443': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '444': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '445': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '446': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '520': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '521': ('cool', 'heat', 'dry'),
    '522': ('auto', 'cool', 'heat', 'dry'),
    '523': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '524': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '525': ('auto', 'cool', 'heat', 'dry'),
    '526': ('auto', 'cool', 'heat', 'dry'),
    '527': ('auto', 'cool', 'heat', 'dry'),
    '528': ('cool', 'dry'),
    '529': ('auto', 'cool', 'heat', 'dry'),
    '530': ('auto', 'cool', 'heat', 'dry'),
    '531': ('auto', 'cool', 'heat', 'dry'),
    '532': ('auto', 'cool', 'heat', 'dry'),
    '533': ('auto', 'cool', 'heat', 'dry'),
    '534': ('cool', 'heat', 'dry'),
    '535': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '536': ('auto', 'cool', 'heat', 'dry'),
    '537': ('auto', 'cool', 'heat', 'dry'),
    '538': ('auto', 'cool', 'heat', 'dry'),
    '539': ('auto', 'cool', 'heat', 'dry'),
    '540': ('auto', 'cool', 'heat', 'dry'),
    '541': ('auto', 'cool', 'heat', 'dry'),
    '542': ('auto', 'cool', 'heat', 'dry'),
    '543': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '544': ('auto', 'cool', 'heat', 'dry'),
    '545': ('cool', 'heat', 'dry'),
    '546': ('auto', 'cool', 'heat', 'dry'),
    '547': ('auto', 'cool', 'heat', 'dry'),
    '600': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '601': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '602': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '603': ('cool', 'fan', 'dry'),
    '604': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '605': ('auto', 'cool', 'fan', 'dry'),
    '606': ('auto', 'cool', 'fan', 'dry'),
    '607': ('auto', 'cool', 'fan', 'dry'),
    '608': ('auto', 'cool', 'fan', 'dry'),
    '609': ('auto', 'cool', 'fan'),
    '610': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '611': ('auto', 'cool', 'dry'),
    '612': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '613': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '614': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '615': ('auto', 'cool', 'fan', 'dry'),
    '616': ('auto', 'cool', 'fan', 'dry'),
    '617': ('cool', 'dry'),
    '618': ('cool', 'fan', 'dry'),
    '619': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '620': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '621': (),
    '622': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '623': ('cool', 'fan', 'dry'),
    '624': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '625': ('cool', 'fan', 'dry'),
    '626': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '627': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '628': ('cool', 'dry'),
    '629': ('auto', 'cool', 'fan', 'dry'),
    '630': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '631': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '632': ('auto', 'cool', 'fan', 'dry'),
    '633': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '634': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '635': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '636': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '637': (),
    '638': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '639': ('auto', 'cool', 'heat'),
    '640': ('auto', 'cool', 'heat', 'dry'),
    '641': ('auto', 'cool', 'dry'),
    '642': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '643': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '644': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '645': ('auto', 'cool', 'fan', 'dry'),
    '646': ('auto', 'cool', 'fan', 'dry'),
    '647': (),
    '648': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '649': ('cool', 'fan', 'dry'),
    '650': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '651': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '652': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '653': ('cool', 'fan', 'dry'),
    '654': (),
    '655': ('auto', 'cool', 'heat', 'fan', 'dry'),
    '656': (),
    '657': ('cool', 'heat', 'fan', 'dry'),
    '658': ('cool', 'heat', 'fan', 'dry'),
    '659': ('cool', 'heat', 'fan', 'dry'),
}

AC_CLASSIC_TEMP_CONTROL_CODES: frozenset[str] = frozenset(['16', '19', '115', '116', '117', '120', '121', '123', '124', '125', '126', '162', '180', '194', '260', '261', '271', '293', '315', '317', '435', '621', '637', '647', '654', '656', '19866', '19868', '19891', '19987', '19988'])

AC_EXTRA_WINDSPEED_CODES: frozenset[str] = frozenset(['19888'])

AC_SHOW_DISPLAY_MOLD_CODES: frozenset[str] = frozenset(['134', '179', '19898', '19968', '19974'])

AC_SINGLE_MODE_CODES: frozenset[str] = frozenset(['281', '19866'])

AC_DEHUMIDIFIER_CODES: frozenset[str] = frozenset(['19966'])

# The two AC_OBSERVED_* sets below are NOT from Firebase Remote Config.
# They track codes for which hardware testing has empirically confirmed
# behavior beyond what the Firebase capability matrix declares (e.g.,
# extra windspeed support that's not in the catalog, or turbo-bit
# responsiveness on specific AC families). The regen tool preserves
# whatever values are in this file across runs.

AC_OBSERVED_EXTRA_WINDSPEED_CODES: frozenset[str] = frozenset()

AC_OBSERVED_TURBO_CODES: frozenset[str] = frozenset()
